name: Test Build
on: [push]
strategy:
  matrix:
    os: [windows, macos]
    build-type: [Release, Debug]
jobs:
  build:
    name: ${{matrix.os}}/${{matrix.build-type}
    runs-on: ${{matrix.os}}-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make build directory
        run: cmake -E make_directory build
      - name: Configure
        working-directory: build
        run: cmake .. -DCMAKE_BUILD_TYPE=${{matrix.build-type}}
      - name: Compile
        working-directory: build
        run: cmake --build .
