name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    name: ${{matrix.os}}/${{matrix.build-type}}
    runs-on: ${{matrix.runs-on}}
    steps:
      - uses: actions/checkout@v2
      - name: Make build directory
        run: cmake -E make_directory build
      - name: Configure
        working-directory: build
        run: |
          cmake .. \
            -DSOURCE_URL=https://github.com/${{github.repository}} \
            -DSOURCE_REF=${{github.sha}} \
            -DCMAKE_BUILD_TYPE=${{matrix.build-type}} \
            "-DCMAKE_INSTALL_PREFIX=$(echo "${{runner.temp}}/install" | tr "\\\\" /)"
        shell: bash
      - name: Compile
        working-directory: build
        run: cmake --build . --config ${{matrix.build-type}}
      - name: Run tests
        working-directory: build
        run: ctest -C ${{matrix.build-type}} --output-on-failure
      - name: Install
        working-directory: build
        run: cmake --install . --config ${{matrix.build-type}}
      - name: Test installation
        working-directory: build
        run: cmake --build . --target install_test --config ${{matrix.build-type}}
      - name: Upload StreamDeckSDK.cmake
        uses: actions/upload-artifact@v2
        with:
          name: StreamDeckSDK.cmake
          path: build/StreamDeckSDK.cmake
    strategy:
      fail-fast: false
      matrix:
        os: [windows, macos, linux]
        build-type: [Release, Debug]
      with:
        os: windows
        runs-on: windows-latest
      with:
        os: macos
        runs-on: macos-latest
      with:
        os: linux
        runs-on: ubuntu-20.04
